### ISSUE TITLE
It's not finding gunicorn

### ISSUE THREAD

**Issue by thesteve0** [zemanel/openshift-diy-django-example#3]
I think the reason I am getting a 503 is that the script is trying to start gunicorn but can't find it.

<snip out all the other git and build stuff>
remote:     no previously-included directories found matching 'doc/src/_build'
remote:   Running setup.py install for South
remote:   Running setup.py install for unipath
remote:   Running setup.py install for doctools
remote:   Running setup.py install for gunicorn
remote:     Installing gunicorn_paster script to /var/lib/openshift/5150d1e3500446a32100030f/app-root/data/virtualenvs/bc79068129ca7bf8efda49506ddf4dd9/bin
remote:     Installing gunicorn script to /var/lib/openshift/5150d1e3500446a32100030f/app-root/data/virtualenvs/bc79068129ca7bf8efda49506ddf4dd9/bin
remote:     Installing gunicorn_django script to /var/lib/openshift/5150d1e3500446a32100030f/app-root/data/virtualenvs/bc79068129ca7bf8efda49506ddf4dd9/bin
remote:   Running setup.py install for pytest
remote:     Installing py.test script to /var/lib/openshift/5150d1e3500446a32100030f/app-root/data/virtualenvs/bc79068129ca7bf8efda49506ddf4dd9/bin
remote:     Installing py.test-2.6 script to /var/lib/openshift/5150d1e3500446a32100030f/app-root/data/virtualenvs/bc79068129ca7bf8efda49506ddf4dd9/bin
remote:   Running setup.py install for pytest-cov
remote:   Running setup.py install for py
remote:   Running setup.py install for cov-core
remote:  
remote:     Wrote pth file for subprocess measurement to /var/lib/openshift/5150d1e3500446a32100030f/app-root/data/virtualenvs/bc79068129ca7bf8efda49506ddf4dd9/lib/python2.6/site-packages/init_cov_core.pth
remote:   Running setup.py install for coverage
remote:     building 'coverage.tracer' extension
remote:     gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c coverage/tracer.c -o build/temp.linux-x86_64-2.6/coverage/tracer.o
remote:     gcc -pthread -shared build/temp.linux-x86_64-2.6/coverage/tracer.o -L/usr/lib64 -lpython2.6 -o build/lib.linux-x86_64-2.6/coverage/tracer.so
remote:     warning: no previously-included files matching '_.pyc' found anywhere in distribution
remote:     Installing coverage2 script to /var/lib/openshift/5150d1e3500446a32100030f/app-root/data/virtualenvs/bc79068129ca7bf8efda49506ddf4dd9/bin
remote:     Installing coverage-2.6 script to /var/lib/openshift/5150d1e3500446a32100030f/app-root/data/virtualenvs/bc79068129ca7bf8efda49506ddf4dd9/bin
remote:     Installing coverage script to /var/lib/openshift/5150d1e3500446a32100030f/app-root/data/virtualenvs/bc79068129ca7bf8efda49506ddf4dd9/bin
remote: Successfully installed Django psycopg2 South unipath doctools gunicorn pytest pytest-cov py cov-core coverage
remote: Cleaning up...
remote: *_\* Executing 'python /var/lib/openshift/5150d1e3500446a32100030f/app-root/runtime/repo/manage.py syncdb --noinput'
remote: Unknown command: 'syncdb'
remote: Type 'manage.py help' for usage.
remote: **\* Executing 'python /var/lib/openshift/5150d1e3500446a32100030f/app-root/runtime/repo/manage.py migrate'
remote: Unknown command: 'migrate'
remote: Type 'manage.py help' for usage.
remote: Executing 'python /var/lib/openshift/5150d1e3500446a32100030f/app-root/runtime/repo/manage.py collectstatic --clear --noinput'
remote: Unknown command: 'collectstatic'
remote: Type 'manage.py help' for usage.
remote: hot_deploy_added=false
remote: PostgreSQL server instance already running
**remote: Unknown command: 'run_gunicorn'**

**Comment by zemanel** [comment]
it may not be activating the virtualenv properly, since i see the deps
installed.

will do a fresh test and get back at you.

are you using the very latest master ?

gtalk: zemanel@zemanel.eu
skype: zemanel_eu
No dia 25 de Mar de 2013 22:57, "Steven Citron-Pousty" <
notifications@github.com> escreveu:

**Comment by thesteve0** [comment]
I am basically using your instructions in the readme - so whatever that
pulls then that is what I get

**Comment by zemanel** [comment]
i'm doing a fresh test and the 'OPENSHIFT_DB_*' shell variables are not available anymore.
I had my test instance created for quite a while, perhaps there were some Openshift feature changes meanwhile that i was not aware ?

I'm updating the configuration, using 'OPENSHIFT_POSTGRESQL_DB_*' specifically.

**Comment by thesteve0** [comment]
My guess is you forgot to add the postgresql cartridge

**Comment by zemanel** [comment]
It was due to the environment variables (fresh tested); my test app was created a looong time ago.

i'm pushing a new release with those changes. I'm using git-flow by the way, so it would be easier if pull requests were made onto develop or a new feature branch it would be cool. but of course i could have stated that on a 'Contributing' section of the docs ^^ which i will also add :-)

**Comment by zemanel** [comment]
Updated the sample project and tested on a fresh app. Some environment variables needed updating (database and diy log directory).

Another sample instance is running at http://djangoexampletest1-zemanel.rhcloud.com.

Followed the "--from-code" approach, but after the command is ran and finishes,  i believe Openshift runs the deployment process which takes some time and meanwhile the instance web response returns a 503, which may confuse users. any suggestions for an improvement ? Perhaps using the git merge approach, so that end users can monitor the deployment process on their shell ?

Thanks.

**Comment by zemanel** [comment]
closing issue as this does not apply anymore
